<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ProblemBankSeeder extends Seeder
{
    public function run(): void
    {
        $problems = [
            [
                'code' => 'PLACAR',
                'name' => 'Quem vai ser reprovado',
                'description' => 'Prof. Wallywow da Universidade da Columbia Britanica esta muito preocupado com a queda do nivel de atencao de seus estudantes. Ele criou uma competicao entre os alunos: o ultimo colocado sera reprovado sumariamente. Os alunos sao ordenados conforme o numero de problemas resolvidos, com empates resolvidos de acordo com a ordem alfabetica dos nomes.',
                'input_description' => 'A entrada e composta de diversas instancias. A primeira linha de cada instancia consiste em um inteiro n (1 <= n <= 100) indicando o numero de alunos. Cada uma das n linhas seguintes contem o nome do aluno (letras minusculas, max 20) e o numero de problemas resolvidos (0-10). A entrada termina com EOF.',
                'output_description' => 'Para cada instancia, imprima "Instancia k" onde k e o numero da instancia. Na linha seguinte imprima o nome do reprovado. Apos cada instancia imprima uma linha em branco.',
                'sample_input' => "4\ncardonha 9\ninfelizreprovado 3\nmarcel 9\ninfelizaprovado 3",
                'sample_output' => "Instancia 1\ninfelizreprovado",
                'time_limit' => 1,
                'memory_limit' => 256,
                'difficulty' => 'easy',
                'tags' => json_encode(['ordenacao', 'strings', 'iniciante']),
                'source' => 'SPOJ Brasil',
                'source_url' => 'https://br.spoj.com/problems/PLACAR/',
            ],
            [
                'code' => 'FATORIAL',
                'name' => 'Fatorial',
                'description' => 'Neste problema voce deve calcular o fatorial de um numero. O fatorial de n (representado por n!) e o produto de todos os inteiros positivos menores ou iguais a n.',
                'input_description' => 'A entrada contem varios casos de teste. Cada caso contem um inteiro N (0 <= N <= 20). A entrada termina com EOF.',
                'output_description' => 'Para cada caso, imprima o valor de N!.',
                'sample_input' => "0\n1\n5\n10",
                'sample_output' => "1\n1\n120\n3628800",
                'time_limit' => 1,
                'memory_limit' => 256,
                'difficulty' => 'easy',
                'tags' => json_encode(['matematica', 'iniciante', 'fatorial']),
                'source' => 'SPOJ Brasil',
                'source_url' => 'https://br.spoj.com/problems/FATORIAL/',
            ],
            [
                'code' => 'F91',
                'name' => 'Funcao 91 de McCarthy',
                'description' => 'A funcao 91 de McCarthy e definida como: M(n) = n - 10, se n > 100; M(n) = M(M(n + 11)), se n <= 100. Dado um inteiro N, calcule M(N).',
                'input_description' => 'A entrada consiste em uma serie de linhas, cada uma contendo um inteiro N. A entrada termina quando N = 0.',
                'output_description' => 'Para cada N da entrada, imprima uma linha contendo "f91(N) = R", onde R e o resultado.',
                'sample_input' => "500\n91\n0",
                'sample_output' => "f91(500) = 490\nf91(91) = 91",
                'time_limit' => 1,
                'memory_limit' => 256,
                'difficulty' => 'easy',
                'tags' => json_encode(['recursao', 'matematica', 'funcoes']),
                'source' => 'SPOJ Brasil',
                'source_url' => 'https://br.spoj.com/problems/F91/',
            ],
            [
                'code' => 'CONTAGEM',
                'name' => 'Nao e Mais um Joguinho Canadense',
                'description' => 'Dois jogadores jogam alternadamente. Comecando com N palitos, cada jogador remove 1, 2 ou 3 palitos por vez. Quem pegar o ultimo palito perde. Determine quem vence assumindo jogo otimo.',
                'input_description' => 'A entrada contem varios casos de teste. Cada caso contem um inteiro N (1 <= N <= 10000), o numero inicial de palitos.',
                'output_description' => 'Para cada caso, imprima "Primeiro" se o primeiro jogador vence, ou "Segundo" caso contrario.',
                'sample_input' => "1\n2\n3\n4",
                'sample_output' => "Segundo\nPrimeiro\nPrimeiro\nPrimeiro",
                'time_limit' => 1,
                'memory_limit' => 256,
                'difficulty' => 'easy',
                'tags' => json_encode(['teoria dos jogos', 'matematica', 'nim']),
                'source' => 'SPOJ Brasil',
                'source_url' => 'https://br.spoj.com/problems/CONTAGEM/',
            ],
            [
                'code' => 'QUADRADO',
                'name' => 'Construtores de Totens',
                'description' => 'Uma tribo constroi totens empilhando blocos quadrados. Dado o numero de blocos disponiveis, determine quantos totens completos podem ser construidos, onde cada totem usa n^2 blocos para algum n >= 1.',
                'input_description' => 'A entrada contem varios casos. Cada linha contem um inteiro B (1 <= B <= 10^9) representando o numero de blocos disponiveis.',
                'output_description' => 'Para cada caso, imprima o numero maximo de totens que podem ser construidos.',
                'sample_input' => "1\n2\n4\n14",
                'sample_output' => "1\n1\n2\n3",
                'time_limit' => 1,
                'memory_limit' => 256,
                'difficulty' => 'medium',
                'tags' => json_encode(['matematica', 'greedy', 'quadrados perfeitos']),
                'source' => 'SPOJ Brasil',
                'source_url' => 'https://br.spoj.com/problems/QUADRADO/',
            ],
            [
                'code' => 'MOEDAS',
                'name' => 'Moedas',
                'description' => 'Dado um valor V e um conjunto de moedas com valores diferentes, determine o numero minimo de moedas necessarias para formar o valor V, ou se e impossivel.',
                'input_description' => 'A primeira linha contem N (numero de tipos de moedas) e V (valor desejado). A segunda linha contem N inteiros representando os valores das moedas.',
                'output_description' => 'Imprima o numero minimo de moedas ou "impossivel" se nao for possivel.',
                'sample_input' => "3 11\n1 5 6",
                'sample_output' => "3",
                'time_limit' => 1,
                'memory_limit' => 256,
                'difficulty' => 'medium',
                'tags' => json_encode(['programacao dinamica', 'moedas', 'dp']),
                'source' => 'SPOJ Brasil',
                'source_url' => 'https://br.spoj.com/problems/MOEDAS/',
            ],
            [
                'code' => 'KRAKOVIA',
                'name' => 'Krakovia',
                'description' => 'Um grupo de amigos quer dividir igualmente uma conta de restaurante. Dado o valor total e o numero de pessoas, calcule quanto cada um deve pagar (divisao inteira).',
                'input_description' => 'Cada caso de teste contem duas linhas: a primeira com N (numero de itens) e a segunda com N valores. A terceira linha contem M (numero de pessoas). Entrada termina com N=0.',
                'output_description' => 'Para cada caso, imprima quanto cada pessoa deve pagar.',
                'sample_input' => "3\n10 20 30\n3\n0",
                'sample_output' => "20",
                'time_limit' => 1,
                'memory_limit' => 256,
                'difficulty' => 'easy',
                'tags' => json_encode(['matematica', 'divisao', 'iniciante']),
                'source' => 'SPOJ Brasil',
                'source_url' => 'https://br.spoj.com/problems/KRAKOVIA/',
            ],
            [
                'code' => 'BOLSA',
                'name' => 'Bolsa de Valores',
                'description' => 'Dado o historico de precos de uma acao, determine o lucro maximo que poderia ser obtido comprando e vendendo a acao uma unica vez.',
                'input_description' => 'A primeira linha contem N, o numero de dias. A segunda linha contem N inteiros representando o preco da acao em cada dia.',
                'output_description' => 'Imprima o lucro maximo possivel. Se nao for possivel ter lucro, imprima 0.',
                'sample_input' => "6\n10 7 5 8 11 2",
                'sample_output' => "6",
                'time_limit' => 1,
                'memory_limit' => 256,
                'difficulty' => 'medium',
                'tags' => json_encode(['array', 'greedy', 'maxima diferenca']),
                'source' => 'SPOJ Brasil',
                'source_url' => 'https://br.spoj.com/problems/BOLSA/',
            ],
            [
                'code' => 'ESPIRAL',
                'name' => 'Espiral',
                'description' => 'Dado um numero N, imprima uma matriz NxN preenchida em espiral, comecando do canto superior esquerdo e indo no sentido horario.',
                'input_description' => 'A entrada contem varios casos. Cada caso contem um inteiro N (1 <= N <= 20). Entrada termina com N=0.',
                'output_description' => 'Para cada caso, imprima a matriz NxN preenchida em espiral.',
                'sample_input' => "3\n4\n0",
                'sample_output' => "1 2 3\n8 9 4\n7 6 5\n\n1 2 3 4\n12 13 14 5\n11 16 15 6\n10 9 8 7",
                'time_limit' => 1,
                'memory_limit' => 256,
                'difficulty' => 'medium',
                'tags' => json_encode(['matriz', 'simulacao', 'espiral']),
                'source' => 'SPOJ Brasil',
                'source_url' => 'https://br.spoj.com/problems/ESPIRAL/',
            ],
            [
                'code' => 'TRAFEGO',
                'name' => 'Trafego',
                'description' => 'Uma cidade tem N cruzamentos conectados por ruas de mao unica. Determine se e possivel ir de qualquer cruzamento para qualquer outro.',
                'input_description' => 'A primeira linha contem N (cruzamentos) e M (ruas). As proximas M linhas contem dois inteiros A e B indicando uma rua de A para B.',
                'output_description' => 'Imprima "SIM" se o grafo e fortemente conexo, "NAO" caso contrario.',
                'sample_input' => "4 4\n1 2\n2 3\n3 4\n4 1",
                'sample_output' => "SIM",
                'time_limit' => 1,
                'memory_limit' => 256,
                'difficulty' => 'hard',
                'tags' => json_encode(['grafos', 'conectividade', 'dfs']),
                'source' => 'SPOJ Brasil',
                'source_url' => 'https://br.spoj.com/problems/TRAFEGO/',
            ],
            [
                'code' => 'SUDOIME',
                'name' => 'Sudoku',
                'description' => 'Verifique se uma solucao de Sudoku 9x9 e valida. Uma solucao valida tem todos os numeros de 1 a 9 em cada linha, coluna e bloco 3x3.',
                'input_description' => 'A entrada contem varios casos. Cada caso consiste em 9 linhas com 9 numeros cada, representando o tabuleiro de Sudoku. Entrada termina com EOF.',
                'output_description' => 'Para cada caso, imprima "SIM" se a solucao e valida, "NAO" caso contrario.',
                'sample_input' => "5 3 4 6 7 8 9 1 2\n6 7 2 1 9 5 3 4 8\n1 9 8 3 4 2 5 6 7\n8 5 9 7 6 1 4 2 3\n4 2 6 8 5 3 7 9 1\n7 1 3 9 2 4 8 5 6\n9 6 1 5 3 7 2 8 4\n2 8 7 4 1 9 6 3 5\n3 4 5 2 8 6 1 7 9",
                'sample_output' => "SIM",
                'time_limit' => 1,
                'memory_limit' => 256,
                'difficulty' => 'medium',
                'tags' => json_encode(['matriz', 'validacao', 'sudoku']),
                'source' => 'SPOJ Brasil',
                'source_url' => 'https://br.spoj.com/problems/SUDOIME/',
            ],
            [
                'code' => 'FUTEBOL',
                'name' => 'Futebol',
                'description' => 'Dado o resultado de varios jogos de futebol, calcule a classificacao final dos times. Vitoria = 3 pontos, Empate = 1 ponto, Derrota = 0 pontos. Desempate por saldo de gols, depois gols marcados, depois ordem alfabetica.',
                'input_description' => 'A primeira linha contem N (numero de times) e M (numero de jogos). Seguem N nomes de times e M resultados no formato "TimeA GoalsA x GoalsB TimeB".',
                'output_description' => 'Imprima a classificacao final com nome, pontos, vitorias, empates, derrotas, gols marcados e sofridos.',
                'sample_input' => "4 6\nBrasil\nArgentina\nAlemanha\nFranca\nBrasil 3 x 1 Argentina\nAlemanha 2 x 2 Franca\nBrasil 1 x 0 Alemanha\nArgentina 1 x 1 Franca\nBrasil 2 x 0 Franca\nArgentina 0 x 1 Alemanha",
                'sample_output' => "Brasil 9 3 0 0 6 1\nAlemanha 4 1 1 1 3 3\nFranca 2 0 2 1 3 4\nArgentina 1 0 1 2 2 6",
                'time_limit' => 1,
                'memory_limit' => 256,
                'difficulty' => 'medium',
                'tags' => json_encode(['ordenacao', 'simulacao', 'strings']),
                'source' => 'SPOJ Brasil',
                'source_url' => 'https://br.spoj.com/problems/FUTEBOL/',
            ],
            [
                'code' => 'CAIXVIAJ',
                'name' => 'Caixeiro Viajante',
                'description' => 'O problema classico do caixeiro viajante: dado um conjunto de cidades e as distancias entre elas, encontre o menor caminho que visita todas as cidades exatamente uma vez e retorna a origem.',
                'input_description' => 'A primeira linha contem N (2 <= N <= 12), o numero de cidades. Seguem N linhas com N inteiros cada, representando a matriz de distancias.',
                'output_description' => 'Imprima a menor distancia total do circuito.',
                'sample_input' => "4\n0 10 15 20\n10 0 35 25\n15 35 0 30\n20 25 30 0",
                'sample_output' => "80",
                'time_limit' => 2,
                'memory_limit' => 256,
                'difficulty' => 'hard',
                'tags' => json_encode(['programacao dinamica', 'bitmask', 'tsp', 'grafos']),
                'source' => 'SPOJ Brasil',
                'source_url' => 'https://br.spoj.com/problems/CAIXVIAJ/',
            ],
            [
                'code' => 'CFATORES',
                'name' => 'Conte os Fatores',
                'description' => 'Dado um numero N, conte quantos fatores primos distintos ele possui.',
                'input_description' => 'A entrada contem varios casos. Cada caso contem um inteiro N (2 <= N <= 10^6). Entrada termina com EOF.',
                'output_description' => 'Para cada caso, imprima o numero de fatores primos distintos de N.',
                'sample_input' => "2\n12\n30",
                'sample_output' => "1\n2\n3",
                'time_limit' => 1,
                'memory_limit' => 256,
                'difficulty' => 'easy',
                'tags' => json_encode(['matematica', 'fatoracao', 'primos']),
                'source' => 'SPOJ Brasil',
                'source_url' => 'https://br.spoj.com/problems/CFATORES/',
            ],
            [
                'code' => 'POPULAR',
                'name' => 'Popularidade',
                'description' => 'Em uma escola, alunos podem indicar outros alunos como populares. A popularidade e transitiva: se A indica B e B indica C, entao A tambem considera C popular. Encontre o aluno mais popular.',
                'input_description' => 'A primeira linha contem N (alunos) e M (indicacoes). As proximas M linhas contem dois inteiros A e B indicando que A considera B popular.',
                'output_description' => 'Imprima o numero de alunos que sao considerados populares por todos os outros.',
                'sample_input' => "3 3\n1 2\n2 1\n2 3",
                'sample_output' => "1",
                'time_limit' => 1,
                'memory_limit' => 256,
                'difficulty' => 'hard',
                'tags' => json_encode(['grafos', 'componentes fortemente conexos', 'dag']),
                'source' => 'SPOJ Brasil',
                'source_url' => 'https://br.spoj.com/problems/POPULAR/',
            ],
            [
                'code' => 'ENGARRAF',
                'name' => 'Engarrafamento',
                'description' => 'Uma cidade tem intersecoes conectadas por ruas. Dado o tempo para atravessar cada rua, encontre o menor tempo para ir de uma intersecao a outra.',
                'input_description' => 'A primeira linha contem N (intersecoes), M (ruas), S (origem) e T (destino). As proximas M linhas contem tres inteiros A, B e C indicando uma rua de A para B com tempo C.',
                'output_description' => 'Imprima o menor tempo ou -1 se nao houver caminho.',
                'sample_input' => "4 4 1 4\n1 2 5\n2 3 5\n3 4 5\n1 4 20",
                'sample_output' => "15",
                'time_limit' => 1,
                'memory_limit' => 256,
                'difficulty' => 'medium',
                'tags' => json_encode(['grafos', 'dijkstra', 'caminho minimo']),
                'source' => 'SPOJ Brasil',
                'source_url' => 'https://br.spoj.com/problems/ENGARRAF/',
            ],
            [
                'code' => 'TESOURO2',
                'name' => 'Tesouro',
                'description' => 'Um mapa do tesouro e representado por uma matriz NxM. Cada celula contem um valor (positivo ou negativo). Encontre o subretangulo com a maior soma.',
                'input_description' => 'A primeira linha contem N e M. As proximas N linhas contem M inteiros cada, representando a matriz.',
                'output_description' => 'Imprima a maior soma possivel de um subretangulo.',
                'sample_input' => "4 5\n1 -2 -3 4 5\n-1 2 3 -4 -5\n4 5 -6 7 8\n-9 10 11 -12 13",
                'sample_output' => "32",
                'time_limit' => 1,
                'memory_limit' => 256,
                'difficulty' => 'hard',
                'tags' => json_encode(['programacao dinamica', 'kadane', 'matriz']),
                'source' => 'SPOJ Brasil',
                'source_url' => 'https://br.spoj.com/problems/TESOURO2/',
            ],
            [
                'code' => 'PAPRIMAS',
                'name' => 'Palavras Primas',
                'description' => 'Uma palavra e prima se a soma dos valores de suas letras (a=1, b=2, ..., z=26) e um numero primo. Determine se uma palavra e prima.',
                'input_description' => 'A entrada contem varios casos. Cada caso contem uma palavra (somente letras minusculas, max 20 caracteres). Entrada termina com EOF.',
                'output_description' => 'Para cada caso, imprima "SIM" se a palavra e prima, "NAO" caso contrario.',
                'sample_input' => "abc\nab",
                'sample_output' => "NAO\nSIM",
                'time_limit' => 1,
                'memory_limit' => 256,
                'difficulty' => 'easy',
                'tags' => json_encode(['strings', 'primos', 'matematica']),
                'source' => 'SPOJ Brasil',
                'source_url' => 'https://br.spoj.com/problems/PAPRIMAS/',
            ],
            [
                'code' => 'RUMO9S',
                'name' => 'Rumo aos 9s',
                'description' => 'Dado um numero N, encontre o menor multiplo de N que consiste apenas de digitos 9. Por exemplo, para N=3, o resultado e 9 (pois 9 = 3*3).',
                'input_description' => 'A entrada contem varios casos. Cada caso contem um inteiro N (1 <= N <= 10000). Entrada termina com EOF.',
                'output_description' => 'Para cada caso, imprima o numero de digitos 9 no menor multiplo ou -1 se nao existir.',
                'sample_input' => "3\n7\n2",
                'sample_output' => "1\n6\n-1",
                'time_limit' => 1,
                'memory_limit' => 256,
                'difficulty' => 'medium',
                'tags' => json_encode(['matematica', 'aritmetica modular', 'bfs']),
                'source' => 'SPOJ Brasil',
                'source_url' => 'https://br.spoj.com/problems/RUMO9S/',
            ],
            [
                'code' => 'FORRO',
                'name' => 'Festa de Forro',
                'description' => 'Em uma festa de forro, casais dancam juntos. Dado o numero de homens e mulheres, determine o numero maximo de casais que podem dancar simultaneamente.',
                'input_description' => 'A entrada contem varios casos. Cada caso contem dois inteiros H e M representando o numero de homens e mulheres. Entrada termina com H=M=0.',
                'output_description' => 'Para cada caso, imprima o numero maximo de casais.',
                'sample_input' => "10 10\n5 10\n0 0",
                'sample_output' => "10\n5",
                'time_limit' => 1,
                'memory_limit' => 256,
                'difficulty' => 'easy',
                'tags' => json_encode(['matematica', 'minimo', 'iniciante']),
                'source' => 'SPOJ Brasil',
                'source_url' => 'https://br.spoj.com/problems/FORRO/',
            ],
        ];

        foreach ($problems as $problem) {
            DB::table('problem_bank')->insert(array_merge($problem, [
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ]));
        }
    }
}
